title: HAQ RESEARCH
description: AI Systems, Architecture & Research Notes

url: "https://haq-research.github.io"
baseurl: ""

author:
  name: Abdul Haq
  email: your-email@example.com
  linkedin: mohammadhaq01
  github: haq-research

# Build settings
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /blogs/:title/

# Collections
collections:
  research:
    output: true
    permalink: /research/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "research"
    values:
      layout: "research"

# Exclude
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
