title: Haq Research
description: AI Systems, Architecture & Research Notes
url: "https://haq-research.github.io"
baseurl: ""

author:
  name: Abdul Haq
  linkedin: https://www.linkedin.com/in/mohammadhaq01/
  github: https://github.com/haq-research

# Build settings
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /posts/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
